### ISSUE TITLE
Service Discovery Error

### ISSUE THREAD

**Issue by tmapfumo** [TomPallister/Ocelot#206]
Dear Tom

I get the following error while trying to use Consul as my service discovery tool. 

2018-01-26 16:22:07.6717|ERROR|Ocelot.Errors.Middleware.ExceptionHandlerMiddleware|Exception caught in global error handler, exception message: Invalid URI: The hostname could not be parsed., exception stack:    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at System.UriBuilder.get_Uri()
   at Ocelot.LoadBalancer.Middleware.LoadBalancingMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.QueryStrings.Middleware.QueryStringBuilderMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Headers.Middleware.HttpRequestHeadersBuilderMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Authorisation.Middleware.AuthorisationMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Claims.Middleware.ClaimsBuilderMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Authentication.Middleware.AuthenticationMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.RequestId.Middleware.RequestIdMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Responder.Middleware.ResponderMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.<Invoke>d__4.MoveNext() RequestId: 0HLB4P0MNJP4O:00000001 : OcelotRequestId - not set

below is my Configuration. 
`{
	"ReRoutes": [{
			"DownstreamPathTemplate": "/{url}",
			"UpstreamPathTemplate": "/customer-service/{url}",
			"UpstreamHttpMethod": ["Options", "Put", "Get", "Post", "Delete"],
			"AddHeadersToRequest": {},
			"AddClaimsToRequest": {},
			"RouteClaimsRequirement": {},
			"AddQueriesToRequest": {},
			"RequestIdKey": "",
			"FileCacheOptions": {
				"TtlSeconds": 15,
				"Region": ""
			},
			"ReRouteIsCaseSensitive": false,
			"ServiceName": "CustomerService",
			"DownstreamScheme": "http",
			"DownstreamHost": "localhost",
			"DownstreamPort": 5200,
			"QoSOptions": {
				"ExceptionsAllowedBeforeBreaking": 3,
				"DurationOfBreak": 10,
				"TimeoutValue": 5000
			},
			"LoadBalancer": "",
			"RateLimitOptions": {
				"ClientWhitelist": [],
				"EnableRateLimiting": false,
				"Period": "",
				"PeriodTimespan": 0.0,
				"Limit": 0
			},
			"AuthenticationOptions": {
				"AuthenticationProviderKey": "",
				"AllowedScopes": []
			},
			"HttpHandlerOptions": {
				"AllowAutoRedirect": true,
				"UseCookieContainer": true
			},
			"UseServiceDiscovery": true
		},
		{
			"DownstreamPathTemplate": "/{url}",
			"UpstreamPathTemplate": "/model-service/{url}",
			"UpstreamHttpMethod": ["Options", "Put", "Get", "Post", "Delete"],
			"AddHeadersToRequest": {},
			"AddClaimsToRequest": {},
			"RouteClaimsRequirement": {},
			"AddQueriesToRequest": {},
			"RequestIdKey": "",
			"FileCacheOptions": {
				"TtlSeconds": 15,
				"Region": ""
			},
			"ReRouteIsCaseSensitive": false,
			"ServiceName": "ModelService",
			"DownstreamScheme": "http",
			"DownstreamHost": "localhost",
			"DownstreamPort": 5400,
			"QoSOptions": {
				"ExceptionsAllowedBeforeBreaking": 3,
				"DurationOfBreak": 10,
				"TimeoutValue": 5000
			},
			"LoadBalancer": "",
			"RateLimitOptions": {
				"ClientWhitelist": [],
				"EnableRateLimiting": false,
				"Period": "",
				"PeriodTimespan": 0.0,
				"Limit": 0
			},
			"AuthenticationOptions": {
				"AuthenticationProviderKey": "",
				"AllowedScopes": []
			},
			"HttpHandlerOptions": {
				"AllowAutoRedirect": true,
				"UseCookieContainer": true
			},
			"UseServiceDiscovery": true
		}
	],
	"GlobalConfiguration": {
		"RequestIdKey": "OcRequestId",
		"ServiceDiscoveryProvider": {
			"Host": "localhost",
			"Port": 8500
		}
	}
}`

What must I change, please assist

**Comment by TomPallister** [comment]
@tmapfumo thanks for trying Ocelot and your interest in the project! 

I have only had a quick look at this so far! Your configuration.json looks OK. If you are using Consul you can remove the following bits from your configuration.

```json
         "DownstreamScheme": "http",
         "DownstreamHost": "localhost",
         "DownstreamPort": 5200,
```

Have you registered services in Consul using the key's ModelService and CustomerService in Consul.

Ocelot will query consul for service entries on the following urls and expect to get back scheme, host and port etc!

/v1/health/service/ModelService
/v1/health/service/CustomerService

Ocelot uses a dotnet consul library that expects whatever consul returns on these endpoints to deserialise to List<ServiceEntry> and a ServiceEntry is...

   var serviceEntryOne = new ServiceEntry()
            {
                Service = new AgentService()
                {
                    Service = serviceName,
                    Address = "localhost",
                    Port = 50881,
                    ID = Guid.NewGuid().ToString(),
                    Tags = new string[0]
                },
            };

The ServiceDiscoveryTests.cs in the AcceptanceTest project is a good place to see how it all work's.

Hopefully this helps a bit! If not let me know and I will have a proper look.

**Comment by tmapfumo** [comment]
Thank you, Tom. I finally found the issue was to do with my AgentServiceRegistration in registering apps in Consul. The Address had a scheme http:// instead of just the IP address, hence the error invalid URI changed my service registrations and all is working now.

'        var registration = new AgentServiceRegistration()
            {
                Checks = new[] { tcpCheck, httpCheck },
                ID = _registrationID,
                Name = _consulConfig.Value.ServiceName,
                Address =$"{uri.Host}",
                Port = uri.Port,
                Tags = new[] { "customer", "CustomerService", "service" }
            };
'

**Comment by TomPallister** [comment]
@tmapfumo awesome, I will add some validation here so that it is more obvious for the next person! Maybe the docs need improving as well!

**Comment by TomPallister** [comment]
wont return service with invalid address or port and logs the problem..now in develop

**Comment by tmapfumo** [comment]
Thank you.
